# frozen_string_literal: true

SUPER_ULTRA_SHORT_WAIT = 0.5
ULTRA_SHORT_WAIT = 1
SHORTEST_WAIT = 2
SHORTER_WAIT = 5
SHORT_WAIT = 10
LONG_WAIT = 15
LONGER_WAIT = 30
LONGEST_WAIT = 45
ULTRA_LONG_WAIT = 60
SUPER_ULTRA_LONG_WAIT = 90
